services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=menuUser
      - MYSQL_PASSWORD=senha123
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=restaurant
    volumes:
      - "./config.d:/etc/mysql/conf.d:ro"